webtalk_init -webtalk_dir D:\\proyecto_integrador\\rtl_projects\\test_micro\\test_micro.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "mar nov 7 19:50:20 2017" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3feklf8tu0j59j5atqme6bgrfn" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.1_5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1510094777016" -context "sdk\\\\hardware/1510094777016"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1510094777016"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1510094777016"
webtalk_add_data -client sdk -key VivadoVersion -value "2016.1" -context "sdk\\\\hardware/1510094777016"
webtalk_add_data -client sdk -key Arch -value "artix7" -context "sdk\\\\hardware/1510094777016"
webtalk_add_data -client sdk -key Device -value "7a100t" -context "sdk\\\\hardware/1510094777016"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1510094777016"
webtalk_add_data -client sdk -key uid -value "1510094955689" -context "sdk\\\\bsp/1510094955689"
webtalk_add_data -client sdk -key hwid -value "1510094777016" -context "sdk\\\\bsp/1510094955689"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1510094955689"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\bsp/1510094955689"
webtalk_add_data -client sdk -key uid -value "1510094967838" -context "sdk\\\\application/1510094967838"
webtalk_add_data -client sdk -key hwid -value "1510094777016" -context "sdk\\\\application/1510094967838"
webtalk_add_data -client sdk -key bspid -value "1510094955689" -context "sdk\\\\application/1510094967838"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1510094967838"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1510094967838"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1510094967838"
webtalk_transmit -clientid 263038946 -regid "" -xml D:\\proyecto_integrador\\rtl_projects\\test_micro\\test_micro.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html D:\\proyecto_integrador\\rtl_projects\\test_micro\\test_micro.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm D:\\proyecto_integrador\\rtl_projects\\test_micro\\test_micro.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
