# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Board 49-26}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/proyecto_integrador/rtl_projects/test_uart/uart.cache/wt [current_project]
set_property parent.project_path D:/proyecto_integrador/rtl_projects/test_uart/uart.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_verilog -library xil_defaultlib {
  D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/sources_1/new/uart_tx.v
  D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/sources_1/new/uart_rx.v
  D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/sources_1/new/mod_m_counter.v
  D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/sources_1/new/fifo.v
  D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/sources_1/imports/new/clk_wiz_0_clk_wiz.v
  D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/sources_1/new/write_unit.v
  D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/sources_1/new/read_unit.v
  D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/sources_1/new/uart_top.v
  D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/sources_1/imports/new/clk_wiz_0.v
  D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/sources_1/new/top.v
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/constrs_1/imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files D:/proyecto_integrador/rtl_projects/test_uart/uart.srcs/constrs_1/imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc]


synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
