# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Board 49-26}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/proyecto_integrador/rtl_projects/test_board/please_work.cache/wt [current_project]
set_property parent.project_path D:/proyecto_integrador/rtl_projects/test_board/please_work.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
read_verilog -library xil_defaultlib D:/proyecto_integrador/rtl_projects/test_board/please_work.srcs/sources_1/new/please.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/proyecto_integrador/rtl_projects/test_board/please_work.srcs/constrs_1/imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files D:/proyecto_integrador/rtl_projects/test_board/please_work.srcs/constrs_1/imports/digilent-xdc-master/Nexys-4-DDR-Master.xdc]


synth_design -top please -part xc7a100tcsg324-1


write_checkpoint -force -noxdef please.dcp

catch { report_utilization -file please_utilization_synth.rpt -pb please_utilization_synth.pb }
