# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: D:/proyecto_integrador/rtl_projects/digilent-xdc-master/Nexys-4-DDR-Master.xdc

# Block Designs: bd/mcu_v1/mcu.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu || ORIG_REF_NAME==mcu}]

# IP: bd/mcu_v1/ip/mcu_microblaze_0_0/mcu_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_microblaze_0_0 || ORIG_REF_NAME==mcu_microblaze_0_0}]

# IP: bd/mcu_v1/ip/mcu_dlmb_v10_0/mcu_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_dlmb_v10_0 || ORIG_REF_NAME==mcu_dlmb_v10_0}]

# IP: bd/mcu_v1/ip/mcu_ilmb_v10_0/mcu_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_ilmb_v10_0 || ORIG_REF_NAME==mcu_ilmb_v10_0}]

# IP: bd/mcu_v1/ip/mcu_dlmb_bram_if_cntlr_0/mcu_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==mcu_dlmb_bram_if_cntlr_0}]

# IP: bd/mcu_v1/ip/mcu_ilmb_bram_if_cntlr_0/mcu_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==mcu_ilmb_bram_if_cntlr_0}]

# IP: bd/mcu_v1/ip/mcu_lmb_bram_0/mcu_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_lmb_bram_0 || ORIG_REF_NAME==mcu_lmb_bram_0}]

# IP: bd/mcu_v1/ip/mcu_mdm_1_0/mcu_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_mdm_1_0 || ORIG_REF_NAME==mcu_mdm_1_0}]

# IP: bd/mcu_v1/ip/mcu_clk_wiz_1_0/mcu_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_clk_wiz_1_0 || ORIG_REF_NAME==mcu_clk_wiz_1_0}]

# IP: bd/mcu_v1/ip/mcu_rst_clk_wiz_1_100M_0/mcu_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mcu_rst_clk_wiz_1_100M_0}]

# IP: bd/mcu_v1/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_gpio_0_0 || ORIG_REF_NAME==mcu_axi_gpio_0_0}]

# IP: bd/mcu_v1/ip/mcu_microblaze_0_axi_periph_0/mcu_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_microblaze_0_axi_periph_0 || ORIG_REF_NAME==mcu_microblaze_0_axi_periph_0}]

# IP: bd/mcu_v1/ip/mcu_axi_uartlite_0_0/mcu_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_axi_uartlite_0_0 || ORIG_REF_NAME==mcu_axi_uartlite_0_0}]

# IP: bd/mcu_v1/ip/mcu_xbar_0/mcu_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_xbar_0 || ORIG_REF_NAME==mcu_xbar_0}]

# IP: bd/mcu_v1/ip/mcu_auto_pc_0/mcu_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_auto_pc_0 || ORIG_REF_NAME==mcu_auto_pc_0}]

# IP: bd/mcu_v1/ip/mcu_auto_pc_1/mcu_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mcu_auto_pc_1 || ORIG_REF_NAME==mcu_auto_pc_1}]

# XDC: bd/mcu_v1/ip/mcu_microblaze_0_0/mcu_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_microblaze_0_0 || ORIG_REF_NAME==mcu_microblaze_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu_v1/ip/mcu_microblaze_0_0/mcu_microblaze_0_0_ooc_debug.xdc

# XDC: bd/mcu_v1/ip/mcu_microblaze_0_0/mcu_microblaze_0_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_dlmb_v10_0/mcu_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_dlmb_v10_0 || ORIG_REF_NAME==mcu_dlmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu_v1/ip/mcu_dlmb_v10_0/mcu_dlmb_v10_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_ilmb_v10_0/mcu_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_ilmb_v10_0 || ORIG_REF_NAME==mcu_ilmb_v10_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu_v1/ip/mcu_ilmb_v10_0/mcu_ilmb_v10_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_dlmb_bram_if_cntlr_0/mcu_dlmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_ilmb_bram_if_cntlr_0/mcu_ilmb_bram_if_cntlr_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_lmb_bram_0/mcu_lmb_bram_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_mdm_1_0/mcu_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_mdm_1_0 || ORIG_REF_NAME==mcu_mdm_1_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu_v1/ip/mcu_mdm_1_0/mcu_mdm_1_0_ooc_trace.xdc

# XDC: bd/mcu_v1/ip/mcu_clk_wiz_1_0/mcu_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_clk_wiz_1_0 || ORIG_REF_NAME==mcu_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/mcu_v1/ip/mcu_clk_wiz_1_0/mcu_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_clk_wiz_1_0 || ORIG_REF_NAME==mcu_clk_wiz_1_0}] {/inst }]/inst ]]

# XDC: bd/mcu_v1/ip/mcu_clk_wiz_1_0/mcu_clk_wiz_1_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_rst_clk_wiz_1_100M_0/mcu_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mcu_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu_v1/ip/mcu_rst_clk_wiz_1_100M_0/mcu_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==mcu_rst_clk_wiz_1_100M_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu_v1/ip/mcu_rst_clk_wiz_1_100M_0/mcu_rst_clk_wiz_1_100M_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_axi_gpio_0_0 || ORIG_REF_NAME==mcu_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu_v1/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_axi_gpio_0_0 || ORIG_REF_NAME==mcu_axi_gpio_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu_v1/ip/mcu_axi_uartlite_0_0/mcu_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_axi_uartlite_0_0 || ORIG_REF_NAME==mcu_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu_v1/ip/mcu_axi_uartlite_0_0/mcu_axi_uartlite_0_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_axi_uartlite_0_0/mcu_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==mcu_axi_uartlite_0_0 || ORIG_REF_NAME==mcu_axi_uartlite_0_0}] {/U0 }]/U0 ]]

# XDC: bd/mcu_v1/ip/mcu_xbar_0/mcu_xbar_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_auto_pc_0/mcu_auto_pc_0_ooc.xdc

# XDC: bd/mcu_v1/ip/mcu_auto_pc_1/mcu_auto_pc_1_ooc.xdc

# XDC: bd/mcu_v1/mcu_ooc.xdc
