# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config  -ruleid {1}  -id {Board 49-26}  -suppress 
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/proyecto_integrador/rtl_projects/test_micro/test_micro.cache/wt [current_project]
set_property parent.project_path D:/proyecto_integrador/rtl_projects/test_micro/test_micro.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
add_files D:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/mcu.bd
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_microblaze_0_0/mcu_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_microblaze_0_0/mcu_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_microblaze_0_0/mcu_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_dlmb_v10_0/mcu_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_dlmb_v10_0/mcu_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_ilmb_v10_0/mcu_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_ilmb_v10_0/mcu_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_dlmb_bram_if_cntlr_0/mcu_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_ilmb_bram_if_cntlr_0/mcu_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_lmb_bram_0/mcu_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_mdm_1_0/mcu_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_mdm_1_0/mcu_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_clk_wiz_1_0/mcu_clk_wiz_1_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_clk_wiz_1_0/mcu_clk_wiz_1_0.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_clk_wiz_1_0/mcu_clk_wiz_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_rst_clk_wiz_1_100M_0/mcu_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_rst_clk_wiz_1_100M_0/mcu_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_rst_clk_wiz_1_100M_0/mcu_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_axi_gpio_0_0/mcu_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_axi_uartlite_0_0/mcu_axi_uartlite_0_0_board.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_axi_uartlite_0_0/mcu_axi_uartlite_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_axi_uartlite_0_0/mcu_axi_uartlite_0_0.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_xbar_0/mcu_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_auto_pc_0/mcu_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all d:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/ip/mcu_auto_pc_1/mcu_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all D:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/mcu_ooc.xdc]
set_property is_locked true [get_files D:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/bd/mcu_v1/mcu.bd]

read_verilog -library xil_defaultlib D:/proyecto_integrador/rtl_projects/test_micro/test_micro.srcs/sources_1/new/top.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/proyecto_integrador/rtl_projects/digilent-xdc-master/Nexys-4-DDR-Master.xdc
set_property used_in_implementation false [get_files D:/proyecto_integrador/rtl_projects/digilent-xdc-master/Nexys-4-DDR-Master.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a100tcsg324-1


write_checkpoint -force -noxdef top.dcp

catch { report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb }
